#!/bin/bash

# Скрипт для автоматической настройки TURN сервера
# Использование: sudo ./setup-turn.sh

set -e

echo "🚀 Настройка TURN сервера..."

# Проверка прав root
if [ "$EUID" -ne 0 ]; then 
    echo "❌ Запустите скрипт с правами root (sudo)"
    exit 1
fi

# Установка coturn
echo "📦 Установка coturn..."
apt update
apt install -y coturn

# Генерация секретного ключа
SECRET_KEY=$(openssl rand -hex 32)
echo "🔑 Сгенерирован секретный ключ: $SECRET_KEY"

# Получение публичного IP
echo "🌐 Определение публичного IP..."
PUBLIC_IP=$(curl -s ifconfig.me)
echo "📍 Публичный IP: $PUBLIC_IP"

# Создание резервной копии конфигурации
if [ -f /etc/turnserver.conf ]; then
    cp /etc/turnserver.conf /etc/turnserver.conf.backup
    echo "💾 Создана резервная копия конфигурации"
fi

# Создание конфигурации
cat > /etc/turnserver.conf << EOF
# TURN Server Configuration
# Generated by setup script

# Сетевые настройки
listening-ip=0.0.0.0
external-ip=$PUBLIC_IP
listening-port=3478

# Диапазон портов для релейных соединений
min-port=49152
max-port=65535

# Релейные соединения
relay-ip=0.0.0.0

# Аутентификация
static-auth-secret=$SECRET_KEY
realm=bigo.1tlt.ru

# Логирование
log-file=/var/log/turnserver.log
verbose

# Безопасность
no-cli
no-tls
no-dtls

# Ограничения
max-bps=1000000
max-allocate-timeout=60
EOF

echo "✅ Конфигурация создана"

# Включение сервиса
echo "🔧 Включение сервиса..."
sed -i 's/^TURNSERVER_ENABLED=0/TURNSERVER_ENABLED=1/' /etc/default/coturn || echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn

# Настройка файрвола
echo "🔥 Настройка файрвола..."
ufw allow 3478/udp
ufw allow 3478/tcp
ufw allow 49152:65535/udp
ufw allow 49152:65535/tcp

# Запуск сервиса
echo "▶️  Запуск TURN сервера..."
systemctl restart coturn
systemctl enable coturn

# Проверка статуса
sleep 2
if systemctl is-active --quiet coturn; then
    echo "✅ TURN сервер успешно запущен!"
else
    echo "❌ Ошибка запуска TURN сервера"
    systemctl status coturn
    exit 1
fi

# Вывод информации
echo ""
echo "═══════════════════════════════════════════════════════"
echo "✅ TURN сервер настроен и запущен!"
echo ""
echo "📋 Информация для настройки приложения:"
echo ""
echo "TURN Server URL: turn:bigo.1tlt.ru:3478"
echo "Secret Key: $SECRET_KEY"
echo ""
echo "Добавьте в .env файлы:"
echo "  NEXT_PUBLIC_WEBRTC_TURN_SERVER=turn:bigo.1tlt.ru:3478"
echo "  NEXT_PUBLIC_WEBRTC_TURN_SECRET=$SECRET_KEY"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📝 Проверка логов: sudo tail -f /var/log/turnserver.log"
echo "📊 Проверка статуса: sudo systemctl status coturn"
echo ""

